### ISSUE TITLE
Error with PHPUnit 10.3.x

### ISSUE THREAD

**Issue by tm1000** [blastcloud/chassis#1]
The error is:
```
TypeError: PHPUnit\Framework\MockObject\Invocation::__construct(): Argument #5 ($object) must be of type PHPUnit\Framework\MockObject\MockObjectInternal|PHPUnit\Framework\MockObject\StubInternal, GuzzleHttp\Psr7\Request given, called in /app/vendor/blastcloud/chassis/src/Expectation.php on line 119
```
Code that is erroring here is: https://github.com/blastcloud/chassis/blob/d59f7f388071cab871342db0296b27d1dd7d0509/src/Expectation.php#L117

The change that happened in phpunit was: https://github.com/sebastianbergmann/phpunit/commit/f8fa35ea0c442f44b0c3f5edfd674d453e2568e4

Workaround: Pin PHPUnit to `10.2.7`

**Comment by adamkelso** [comment]
Hey @tm1000 ,

Thanks for pointing this out. I've issued a new release `1.0.8` for PHPUnit 10. It's also backwards compatible with all versions of PHPUnit 10. Let me know if something doesn't seem to work for you. 

Likewise, if you're using Guzzler or Hybrid, I've incremented both with 0.0.1 increments just to update the recommended lock file with this version.

**Comment by tm1000** [comment]
@adamkelso Thanks! Guzzler is awesome and such a great tool. Thanks for your contributions to Open Source!

**Comment by adamkelso** [comment]
@tm1000 Thank you so much! It's my pleasure, and really happy to know people are using it.
