### ISSUE TITLE
Using Guzzler and Hybrid at the same time is not possible

### ISSUE THREAD

**Issue by jdreesen** [blastcloud/chassis#2]
Hi, we are transitioning from Guzzle to Symfony HttpClient in one of our projects and have just installed Hybrid alongside Guzzler, but now all our Guzzler tests are failing because Hybrid is overriding Guzzler's expectation macros. This is unfortunate because it will be some time before we can complete the transition and get rid of Guzzle.

The problem is as follows:
```
TypeError : {closure}(): Argument #1 ($expectation) must be of type BlastCloud\Hybrid\Expectation, BlastCloud\Guzzler\Expectation given
 /var/www/vendor/blastcloud/hybrid/src/macros.php:8
 /var/www/vendor/blastcloud/chassis/src/Traits/Macros.php:40
 /var/www/vendor/blastcloud/chassis/src/Expectation.php:58
 /var/www/tests/Integration/AppBundle/AvailabilityNotice/Service/AvailabilityNoticeServiceTest.php:128
```

The problem seems to be that `\BlastCloud\Chassis\Traits\Macros::$macros` is static, so that both libraries use the same storage and overwrite each other.

**Comment by adamkelso** [comment]
@jdreesen Thanks for bringing this to my attention. That's honestly a scenario I never considered. Do you have a solution in mind? I can play around with a couple ideas, but if you've already got anything working, I'd love any idea you have.

**Comment by jdreesen** [comment]
Not at the moment, sorry. I haven't had time to look into it yet, and I won't get around to it next week at least.

**Comment by adamkelso** [comment]
@jdreesen Ok, I think I got it. All three packages have new releases, and the sample project I created with both libraries now works with tests that use both Guzzler and Hybrid. I'm closing for now, but please let me know if this did not fix it and we need to reopen.
